# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ShiftJIS-String
version:      1.08
version_from: String.pm
installdirs:  site
requires:
    Carp:                          0
    DynaLoader:                    0
    Exporter:                      0
    strict:                        0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
